### ISSUE TITLE
Inappropriate nav menu structure for mobile displays

### ISSUE THREAD

**Issue by sansaid** [Alisina92/Surfing-Project#1]
Hey @Alisina92 , there are two issues with the nav menu when looking at it from mobile:

1. The hamburger icon is not inline with the nav menu
2. The nav menu should not be horizontal but vertical

We could address both issues by using flexbox with `#nav-menu` (I noticed you used `display: block` with a `flex-direction` attribute, which are incompatible) and `#menu-bar`, and make the `flex-direction` of the `#menu-bar` vertical.

Will elaborate further on a call and follow up here. 💯

**Comment by Alisina92** [comment]
I have applied the following feedback to the hamburger menu know the hamburger is icon is visible but menu is not.

**Comment by sansaid** [comment]
Closing this now as it's resolved since commit b3a7f581bafbb0240faa253e1caa759a6214da3d.
