### ISSUE TITLE
Message input field starts with unnecessary indent levels

### ISSUE THREAD

**Issue by sansaid** [Alisina92/Surfing-Project#2]
Hey @Alisina92 , going through your site, found that the message field starts off heavily indented. Can this be improved?

![image](https://user-images.githubusercontent.com/47756528/78454802-3b467f00-7692-11ea-9a19-b4affa2d5f63.png)

**Comment by Alisina92** [comment]
Fixed it there shouldn't be a space between <texterea></texterea>tags
