### ISSUE TITLE
Unneccessary "Enter" before contact fields

### ISSUE THREAD

**Issue by sansaid** [Alisina92/Surfing-Project#3]
The contact fields all start with "Enter" which isn't necessary. You can update this by just replacing with "First name", "Last name", "Email", "Message", etc. Would go one step further and combine "First name" and "Last name" into one field called "Name".

![image](https://user-images.githubusercontent.com/47756528/78454860-9aa48f00-7692-11ea-947a-e040c4063b39.png)

**Comment by Alisina92** [comment]
Done
